import{a as b,i as p,S as v}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function l(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="48435213-edc98ac088ac3c077da86a508",m=(r,t)=>{const s={params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}};return b.get("https://pixabay.com/api/",s)},y=r=>r.map(({webformatURL:t,largeImageURL:s,tags:l,likes:e,views:o,comments:a,downloads:L})=>`<a href="${s}" class="gallery-item">
  <div class="photo-card">
  <img src="${t}" alt="${l}" loading="lazy" width="360" />
  <div class="photo-info">
    <p class="photo-info-item">Likes<span>${e}</span></p>
	<p class="photo-info-item">Views<span>${o}</span></p>
	<p class="photo-info-item">Comments<span>${a}</span></p>
	<p class="photo-info-item">Downloads<span>${L}</span></p>
  </div>
  </div>
  </a>`).join(""),f=document.querySelector(".form-search"),u=document.querySelector(".gallery"),i=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");let c=1,d="",h;i.style.display="none";const w=async r=>{try{if(r.preventDefault(),u.innerHTML="",i.style.display="block",d=r.currentTarget.elements.user_query.value.trim(),d===""){p.warning({title:"Warning",position:"topRight",message:"Please enter a search query!"});return}c=1,n.classList.add("is-hidden");const{data:t}=await m(d,c);if(i.style.display="none",!t.hits.length){p.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const s=y(t.hits);u.insertAdjacentHTML("beforeend",s),h=new v(".gallery-item",{captions:!0,captionsData:"alt",captionDelay:250}),h.refresh(),f.reset(),t.totalHits>1&&(n.classList.remove("is-hidden"),n.addEventListener("click",g))}catch{i.style.display="none"}};f.addEventListener("submit",w);const g=async r=>{i.style.display="block";try{c++;const{data:t}=await m(d,c),s=y(t.hits);u.insertAdjacentHTML("beforeend",s),h.refresh(),c*15>=t.totalHits&&(p.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("is-hidden"),n.removeEventListener("click",g)),P(),i.style.display="none"}catch{p.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."})}},P=()=>{const{height:r}=u.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
